services:
  chroma:
    container_name: web3-assistant-chroma-db
    image: chromadb/chroma
    volumes:
      - ./data/chroma-data:/data
    ports:
      - "6300:6300"
    networks:
      - vector-network

  api:
    container_name: web3-assistant-vector-api
    build: .
    command:
      [
        "uvicorn",
        "src.vector_storage.chroma_service:app",
        "--host",
        "0.0.0.0",
        "--port",
        "6400",
        "--reload",
      ]
    environment:
      - CHROMADB_HOST=chroma
      - CHROMADB_PORT=8000
      - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - "6400:6400"
    depends_on:
      - chroma
    networks:
      - vector-network
      - web3-assistant-network
    volumes:
      - ./src:/app/src

networks:
  vector-network:
    driver: bridge
  web3-assistant-network:
    external: true
